'use client'
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

// import Header from '@/app/admin/_components/header';
import MarginWidthWrapper from '@/components/margin-width-wrapper';
import PageWrapper from '@/components/page-wrapper';
import SideNav from '@/app/admin/_components/side-nav';
import HeaderMobileAdmin from '@/app/admin/_components/header-mobile-admin';
import { useEffect } from 'react';
import { useRouter } from 'next/navigation';
import Header from './_components/header';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'bipMED-Admin',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const router = useRouter();

  useEffect(() => {
    // Cek token di localStorage
    const token = localStorage.getItem('authToken');

    if (!token) {
      // Kalau tidak ada token, redirect ke halaman login
      router.push('/auth/login');
    }
  }, [router]);

  return (
    <html lang="en">
      <body className={`bg-white ${inter.className} h-screen overflow-hidden`}>
        <div className="flex flex-col md:flex-row h-full">
          <SideNav />
          <main className="flex-1 flex flex-col h-full">
            <MarginWidthWrapper className="flex flex-col h-full overflow-hidden">
              <Header />
              <HeaderMobileAdmin />
              <PageWrapper className="flex-1 overflow-y-auto">{children}</PageWrapper>
            </MarginWidthWrapper>
          </main>
        </div>
      </body>
    </html>
  );
}
